### PR TITLE
Add option to include IO500 in image

### PR DESCRIPTION
**Pull request by lsitkiew**
Signed-off-by: Łukasz Sitkiewicz <lukasz.sitkiewicz@intel.com>

### CODE REVIEW

**Comment by johannlombardi** [comment]
@markaolson could you please inspect?

**Comment by markaolson** [comment]
I talked to @lsitkiew about this.  Since we pull the mpifileutils and io500 installation scripts out of the images/scripts directory in PR9 I would prefer to not put them back.  @cboneti can chime in here but I'm pretty sure he would agree. 

I would like to add hook in the packer scripts that allow anyone to specify a list of scripts they want packer to run during the image build.  With that feature in place we can leave the install_mpifileutils.sh and install_io500-sc21.sh scripts in the terraform/examples/io500 directory and have the ./start.sh specify that those scripts be run when it calls images/make_images.sh.

This way @lsitkiew and his team can still build daos-client images with mpifileutils and io500 in them and we can keep the images/scripts directory clean (only scripts for installing DAOS).

Does this sound like a good solution?

**Comment by cboneti** [comment]
> I talked to @lsitkiew about this. Since we pulled the mpifileutils and io500 installation scripts out of the images/scripts directory in PR9 I would prefer to not put them back. @cboneti can chime in here but I'm pretty sure he would agree.
> 
> I would like to add a "hook" in the packer scripts that will allow anyone to specify a list of scripts they want packer to run during the image build. With that feature in place we can leave the install_mpifileutils.sh and install_io500-sc21.sh scripts in the terraform/examples/io500 directory and have the terraform/examples/io500/start.sh script specify that those scripts be run when it calls images/make_images.sh.
> 
> This way @lsitkiew and his team can still build daos-client images with mpifileutils and io500 in them and we can keep the images/scripts directory clean (only scripts for installing DAOS).
> 
> Does this sound like a good solution?

I agree with @markaolson here. It can start by being a simple command line option that includes the one script if that is easier.

**Comment by lsitkiew** [comment]
This changes are no longer needed. I close this PR.

**Pull request closed without merging**
